### ISSUE TITLE
Day1 회고

### ISSUE THREAD

**Issue by Hyune-c** [Hamill210/java-was#4]
## 오늘한 것
- [ ] http://localhost:8080/index.html 로 접속했을 때 webapp 디렉토리의 index.html 파일을 읽어 클라이언트에 응답합니다.
    - index.html 호출 성공
    - css 호출 실패
    
## 내일 할 것
- Step1. 요구사항 2

## 키워드
- favicon.ico
- 이게 되는 이유  
`!"".equals(line = br.readLine())`
- 프로그램을 종료해도 Listen 이 남아있는 이유
-  Http request, response Header 만 공부
    - request line

**Comment by hanurii** [comment]
좋은점
* 내가 잘 몰랐던 부분들을 짝에게 많이 배울 수 있어서 좋았다.
* 짝에게 물어봤을 때 잘 대답해 주셔서 좋았다.
* 잘 모르는 것에 대해서 같이 찾고 해결하는 과정이 좋았다.
* 부족한 지식을 서로 채워주는 과정이 좋았다.
* 같이 문제를 해결하는 성취감이 좋았다.

나쁜점
* 단님이 애로사항이 있을 때 구체적으로 말을 해주면 좋겠다

**Comment by Hyune-c** [comment]
본격적인 페어프로그래밍은 처음해봐서 어떻게 시작해야될지 감을 잡는데 오래 걸렸습니다.
앞오로도 많은 프로젝트를 해야되기에 Ground Rule 과 Repo 산출물 관리를 효율적으로 할 수 있는 방법을 생각해봐야 될 것 같습니다.

평소 혼자하는 성격이어다보니 어색했지만 서로의 의견을 공유하는 시간이 재미있었습니다. 
의견을 나누고 나은 산출물을 만들수 있는 방법론에 대해 좀 더 궁리해보고 싶습니다.

`그리고 제가 받는 피드백의 수위는 높을수록 좋습니다.`

감사합니다.

**Comment by Hyune-c** [comment]
- favicon.ico 란?
  - 인터넷 웹 브라우저의 탭에 보이는 아이콘
  - 우리의 프로그램에는 webapp 경로에 favicon 이 존재하기에 신경쓰지 않아도 됩니다.

- `!"".equals(line = br.readLine())` 가 되는 이유  
  - HTTP header 와 body 는 empty line 을 기준으로 구분됩니다.
  - bufferedReader 의 readLine() 메소드는 개행 후 문장을 가져옴으로 빈 문자열이 equals 되는 경우는 empty line 일 때 뿐입니다.

  - `empty line : CR(carriage return, 0x0d) + LF(line feed, 0x0a)`

-  Http request, response Header 공부
    - https://github.com/Hyune-c/TIL/blob/master/CS/Http.md#request-response

- line이 null 값인 경우에 대한 예외 처리도 해야 한다. 그렇지 않을 경우 무한 루프에 빠진다.(if (line == null) { return;})
  - 정확한 이유를 모르겠습니다.
- 프로그램을 종료해도 Listen 이 남아있는 이유
  - Pass
